config/routes.rb
Rails.application.routes.draw do
  resources :doctors
  resources :histories
  resources :bentos
  devise_for :users

  root 'histories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bento.rb
class Bento < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  has_many :history_details, dependent: :delete_all
  accepts_nested_attributes_for :history_details, allow_destroy: true

  validates :destination, presence: true
end

app/models/history_detail.rb
class HistoryDetail < ApplicationRecord
  belongs_to :history
  belongs_to :doctor
  belongs_to :bento

  validates :doctor_id, presence: true
  validates :bento_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/bentos_controller.rb
class BentosController < ApplicationController
  before_action :set_bento, only: [:show, :edit, :update, :destroy]

  # GET /bentos
  # GET /bentos.json
  def index
    @bentos = Bento.all
  end

  # GET /bentos/1
  # GET /bentos/1.json
  def show
  end

  # GET /bentos/new
  def new
    @bento = Bento.new
  end

  # GET /bentos/1/edit
  def edit
  end

  # POST /bentos
  # POST /bentos.json
  def create
    @bento = Bento.new(bento_params)

    respond_to do |format|
      if @bento.save
        format.html { redirect_to @bento, notice: 'Bento was successfully created.' }
        format.json { render :show, status: :created, location: @bento }
      else
        format.html { render :new }
        format.json { render json: @bento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bentos/1
  # PATCH/PUT /bentos/1.json
  def update
    respond_to do |format|
      if @bento.update(bento_params)
        format.html { redirect_to @bento, notice: 'Bento was successfully updated.' }
        format.json { render :show, status: :ok, location: @bento }
      else
        format.html { render :edit }
        format.json { render json: @bento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bentos/1
  # DELETE /bentos/1.json
  def destroy
    @bento.destroy
    respond_to do |format|
      format.html { redirect_to bentos_url, notice: 'Bento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bento
      @bento = Bento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bento_params
      params.require(:bento).permit(:name, :url)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = current_user.histories.order(id: :desc)
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = current_user.histories.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = current_user.histories.new(history_params)
    @history.history_at = Time.current

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = current_user.histories.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:destination, history_details_attributes: [:id, :doctor_id, :bento_id, :comment, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bentos_helper.rb
module BentosHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/bentos/_form.html.erb
<%= simple_form_for(@bento) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.input :url %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bentos/edit.html.erb
<h1>Editing Bento</h1>

<%= render 'form', bento: @bento %>

<%= link_to 'Show', @bento %> |
<%= link_to 'Back', bentos_path %>

app/views/bentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お弁当一覧</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bentos.each do |bento| %>
      <tr>
        <td><%= bento.name %></td>
        <td><%= bento.url %></td>
        <td><%= link_to 'Show', bento %></td>
        <td><%= link_to 'Edit', edit_bento_path(bento) %></td>
        <td><%= link_to 'Destroy', bento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bento', new_bento_path %>

app/views/bentos/new.html.erb
<h1>New Bento</h1>

<%= render 'form', bento: @bento %>

<%= link_to 'Back', bentos_path %>

app/views/bentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bento.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bento.url %>
</p>

<%= link_to 'Edit', edit_bento_path(@bento) %> |
<%= link_to 'Back', bentos_path %>

app/views/doctors/_form.html.erb
<%= simple_form_for(@doctor) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/histories/_form.html.erb
<%= simple_nested_form_for(@history) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :destination %>

    <%= f.fields_for :history_details do |history_detail_form| %>
      <%= history_detail_form.input :doctor_id, collection: Doctor.order(:id), include_blank: false %>
      <%= history_detail_form.input :bento_id, collection: Bento.order(:id), include_blank: false %>
      <%= history_detail_form.input :comment %>
      <%= history_detail_form.link_to_remove "この行を削除" %>
    <% end %>
    <p><%= f.link_to_add "行を追加", :history_details %></p>

  </div>


  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>History at</th>
      <th>Destination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.user.email %></td>
        <td><%= history.history_at %></td>
        <td><%= history.destination %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @history.user.email %>
</p>

<p>
  <strong>History at:</strong>
  <%= @history.history_at %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @history.destination %>
</p>

<hr>

<table>
  <tr>
    <th>先生</th>
    <th>弁当</th>
    <th>弁当URL</th>
    <th>コメント</th>
  </tr>
  <% @history.history_details.each do |history_detail| %>
  <tr>
    <td><%= history_detail.doctor.name %></td>
    <td><%= history_detail.bento.name %></td>
    <td><%= history_detail.bento.url %></td>
    <td><%= history_detail.comment %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Obento</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header class="main_header">
  		<h1>お弁当</h1>
  	</header>
  	<nav class="global_nav">
  		<ul>
  			<li><a href="/">注文履歴</a></li>
  			<li><a href="/doctors">先生一覧</a></li>
  			<li><a href="/bentos">お弁当の一覧</a></li>
  		</ul>
  	</nav>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>